defaults:
  - base

name: Line_seq
path: your_datasets_path/Ev-LineSeq/
ev_repr_name: 'stacked_histogram_ne=10000_nbins=10'
sequence_length: 11
resolution_hw: [260, 346]
downsample_by_factor_2: False
only_load_end_labels: False