defaults:
  - base

name: Wireframe_seq
path: 'your_datasets_path/Ev-WireframeSeq'
ev_repr_name: 'stacked_histogram_ne=10000_nbins=10'
sequence_length: 11
resolution_hw: [240, 320]
downsample_by_factor_2: False
only_load_end_labels: False